apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: firefly-iii
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`budget.elposhox.dev`)
    services:
    - kind: Service
      name: firefly-iii
      port: 80
