---
apiVersion: v1
kind: Service
metadata:
  name: firefly-iii
  labels:
    app: firefly-iii
    app.kubernetes.io/instance: firefly-iii-prd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: firefly-iii
    app.kubernetes.io/part-of: firefly-iii
    homelab.local/OwnedBy: ElPoshoX
spec:
  selector:
    app: firefly-iii
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: firefly-iii
    homelab.local/OwnedBy: ElPoshoX
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  internalTrafficPolicy: Cluster
