# Prometheus Ingress
# Link: https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/
#
# Exposes Prometheus web UI via Traefik IngressRoute

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    app.kubernetes.io/name: prometheus
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prometheus.elposhox.dev`)
      kind: Rule
      services:
        - name: prometheus
          port: 9090
  tls:
    certResolver: letsencrypt-prod
