apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: myspeed
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`speedtest.elposhox.dev`)
    services:
    - kind: Service
      name: myspeed
      port: 80
  tls: {}
