---
apiVersion: v1
kind: Service
metadata:
  name: myspeed
  labels:
    app: myspeed
    app.kubernetes.io/instance: myspeed-prd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: myspeed
    app.kubernetes.io/part-of: myspeed
    homelab.local/OwnedBy: ElPoshoX
spec:
  selector:
    app: myspeed
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: myspeed
    homelab.local/OwnedBy: ElPoshoX
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5216
  internalTrafficPolicy: Cluster
