# Grafana Base Configuration
# Link: https://kustomize.io/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/part-of: grafana

resources:
  - namespace.yaml
  - grafana-rbac.yaml
  - grafana-deployment.yaml
